homepage:
    path: '/'
    controller: Default
    action: index

post_create:
    path: '/post/create'
    controller: Default
    action: create

post:
    path: '/post/:id'
    controller: Default
    action: post
    requirements:
        ':id': '[0-9]+'